### ISSUE TITLE
Leer cap. 1 y 2 libro Android OpenCV

### ISSUE THREAD

**Issue by jorgenavarroglez** [DanielBeato/GESPRO_PracticaGestionTareas_1718#1]
- Chapter 1: Setting Up OpenCV, covers the steps to set up OpenCV and an Android development environment, including Eclipse and Android SDK.

- Chapter 2: Working with Camera Frames, shows how to integrate OpenCV into an Android Java app that can preview, capture, save, and share photos.

**Comment by DanielBeato** [comment]
VAMOS vamos, empezamos de nuevo con la cabeza bien alta equipo!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
