### ISSUE TITLE
Grabación de videos

### ISSUE THREAD

**Issue by jng0020** [DanielBeato/GESPRO_PracticaGestionTareas_1718#17]
Grabar vídeos en el colmenar intentando recoger todas las situaciones que se podrá encontrar la app (sombras, solapamiento de abejas...).

**Comment by DanielBeato** [comment]
Que buena idea!!! Dale que sí, sigue así y grabate unos buenos videos con las abejas que tú sí que sabes crack.

**Comment by jng0020** [comment]
He realizado las grabaciones desde dos posiciones, una frontal y otra cenital con un cartón blanco en el suelo. Creo que con la segunda obtendremos mejores resultados, ya que evitamos que haya grandes diferencias de perspectiva en las abejas y además la superficie del cartón facilitará la extracción del fondo.
![image](https://user-images.githubusercontent.com/33248327/32350489-cd8e7100-c01a-11e7-9b7f-837cb137ad59.png)
![image](https://user-images.githubusercontent.com/33248327/32350494-d2a2ca38-c01a-11e7-810d-ef1d774b1d54.png)
He subido todos los vídeos a YouTube y he creado una página en la wiki para agruparlos:
[https://github.com/davidmigloz/go-bees/wiki/Video-Dataset](https://github.com/davidmigloz/go-bees/wiki/Video-Dataset)
