### ISSUE TITLE
Elegir herramienta de gestión de proyecto

### ISSUE THREAD

**Issue by jng0020** [DanielBeato/GESPRO_PracticaGestionTareas_1718#2]
**Herramientas consideradas:**

- ZenHub
- Trello
- Waffle
- VersionOne
- XP-Dev

**Herramienta elegida:**

- [ZenHub](https://www.zenhub.com/)

ZenHub es una herramienta de gestión de proyectos totalmente integrada en GitHub. Proporciona un tablero canvas en donde cada tarea representada se corresponde con un issue nativo de GitHub. Cada tarea se puede priorizar dependiendo de su posición en la lista, se le puede asignar una estimación, uno o varios responsables y el sprint al que pertenece. ZenHub también permite visualizar el gráfico burndown de cada sprint. Es gratuita para proyectos pequeños (max. 5 colaboradores) o proyectos open source.

**Comment by mus0007** [comment]
**Sigue así, CRACK**

**Comment by jng0020** [comment]
Estamos trabajando en ello bro!

**Comment by DanielBeato** [comment]
Me gusta, me gusta, buena elección, gran estudio y desarrollo; aunque para próximas ocasiones a Wikipedia le gustaría que referenciases sus contenidos.
Un saludo Crack.
