### ISSUE TITLE
Diseñar logo

### ISSUE THREAD

**Issue by DanielBeato** [DanielBeato/GESPRO_PracticaGestionTareas_1718#24]
Diseñar un logo representativo para la app.

**Comment by DanielBeato** [comment]
![image](https://user-images.githubusercontent.com/33248339/32329423-5c0b5418-bfdd-11e7-9e17-440f85f0995e.png)

**Comment by DanielBeato** [comment]
Pues yo esto lo veo bien y tal, me gustan las abejas, me gustan los hipsters y me gusta el wiki con sus onditas, así que una abeja hipster con ondas es la solución. ¿Qué creeis @mus0007 @jng0020 @AlissonRoch ? 
Saludos desde Invernalia.

**Comment by mus0007** [comment]
Buenas tardes querido señor de Invernalia, le queriamos comunicar que como siga usted comentando los issues con sentido irónico le pasará factura. Recuerde lo que le pasó a su querido amigo Ned Stark.

Un saludo cordial desde la casa Lannister. 

![gif](http://i.imgur.com/K8xRUaA.gif)
