### ISSUE TITLE
Desarrollar aplicación java

### ISSUE THREAD

**Issue by jng0020** [DanielBeato/GESPRO_PracticaGestionTareas_1718#32]
Desarrollar una aplicación en Java con OpenCV que permita leer un archivo de vídeo para posteriormente aplicarle los algoritmos de visión artificial propicios.

**Comment by DanielBeato** [comment]
Vamos Jorge sal a bailar, que tú lo haces fenomenal!!!! Tu cuerpo se mueve como una palmera... Suave, suave, su su suave!
