### ISSUE TITLE
Realizar nuevas grabaciones en el colmenar

### ISSUE THREAD

**Issue by DanielBeato** [DanielBeato/GESPRO_PracticaGestionTareas_1718#36]
Ahora que se conocen las condiciones idóneas a la hora de grabar, se deben tomar nuevos vídeos antes de que sea demasiado tarde.

**Comment by jorgenavarroglez** [comment]
Graba Graba a las abejitas cruck!

**Comment by arc0067** [comment]
Voy a entrar a ayudarte para acabar antes!!!!!

**Comment by DanielBeato** [comment]
MUCHAS GRACIAS @arc0067 !!!!!

**Comment by DanielBeato** [comment]
Añadidas al dataset: https://github.com/davidmigloz/go-bees/wiki/Video-Dataset
