### ISSUE TITLE
Elegir IDE

### ISSUE THREAD

**Issue by AlissonRoch** [DanielBeato/GESPRO_PracticaGestionTareas_1718#4]
**Herramientas consideradas:**

- Android Studio

- Eclipse

**Herramienta elegida:**

- Android Studio

Android Studio es el IDE oficial para el desarrollo de aplicaciones Android. Está basado en IntelliJ IDEA de JetBrains. Proporciona soporte para Gradle, emulador, editor de layouts, refactorizaciones específicas de Android, herramientas Lint para detectar problemas de rendimiento, uso, compatibilidad de versión, etc.

No se descarta el uso de algún otro IDE para la realización de prototipos fuera de la plataforma Android.

**Comment by DanielBeato** [comment]
Me parece que está muy bien elegida la herramienta de documentación, sí señor!!!
