### ISSUE TITLE
Elegir el mejor algoritmo de BS

### ISSUE THREAD

**Issue by AlissonRoch** [DanielBeato/GESPRO_PracticaGestionTareas_1718#40]
De los algoritmos implementados en el prototipo, realizar una comparativa con varias parametrizaciones para ver cual nos provee mejores resultados.

**Comment by AlissonRoch** [comment]
**Descartados:**

`BackgroundSubtractorKNN` descartado por tener tiempo de ejecución elevados (de media 25ms).
Diferencia de frames: descartado por detectar las abejas por duplicado.

Se consideran para **parametrización:**

`accumulateWeighted`
`BackgroundSubtractorMOG2`

**Comment by AlissonRoch** [comment]
`BackgroundSubtractorMOG2` ha sido el que mejor resultado ha proporcionado. Es más estable y diferencia las sombras de las abejas. Su tiempo de ejecución es algo superior al de accumulateWeighted, 4ms vs 2ms, pero entra dentro de lo aceptable.

Se ha implementado en la DevelopmentPlatform permitiendo modificar los parámetros más relevantes.

**Comment by jng0020** [comment]
Me parece bien el que has elegido Alisson! sigue así crack
