### ISSUE TITLE
Realizar nuevas grabaciones en el colmenar

### ISSUE THREAD

**Issue by jng0020** [DanielBeato/GESPRO_PracticaGestionTareas_1718#48]
Ahora que se conocen las condiciones idóneas a la hora de grabar, se deben tomar nuevos vídeos antes de que sea demasiado tarde.

**Comment by DanielBeato** [comment]
CUIDADO CON LAS ABEJAS DEBES TENER JOVEN PADAWAN!!!!

**Comment by jng0020** [comment]
Añadidas al dataset: [https://github.com/davidmigloz/go-bees/wiki/Video-Dataset](https://github.com/davidmigloz/go-bees/wiki/Video-Dataset)
