### ISSUE TITLE
Elegir herramientas de testing

### ISSUE THREAD

**Issue by mus0007** [DanielBeato/GESPRO_PracticaGestionTareas_1718#5]
**Herramientas elegidas:**

- [Robolectric](http://robolectric.org/)

Robolectric es un framework para la realización de test unitarios que permite la ejecución de los test sin la necesidad de utilizar un emulador (lento). Ya que se encarga de gestionar el inflado de las vistas, cargar los recursos y muchas otras operaciones que permiten ejecutar los test directamente en la JVM pero como si de un dispositivo real se tratara.

- [Mockito](http://site.mockito.org/)

Mockito es un framework de mocking que permite crear objetos mock fácilmente. Estos objetos simulan parte del comportamiento de una clase. Mockito está basado en EasyMock, mejorando su sintaxis haciendo los test más simples y fáciles de leer y con mensajes de error descriptivos.

- [Espresso](https://developer.android.com/training/testing/espresso/index.html)

Espresso es un framework de testing para Android includo en la librería de soporte para testing en Android. Provee una API para escribir UI test que simulen las interacciones de usuario con la app.

- [Travis](https://travis-ci.org/)

Travis es una plataforma de integración continua en la nube para proyectos alojados en GitHub. Permite realizar una build del proyecto y testearla automaticamente cada vez que se realiza un commit, devolviendo un informe con los resultados. Es gratuita para proyectos open source. El soporte para Android está en versión beta (si tuviésemos algún problema se podría utilizar en su defecto CircleCI).

- [Coveralls](https://coveralls.io/)

Coveralls es una herramienta que permite medir el porcentaje de código que está cubierto por un test. Es gratuita para proyectos open source.

**Comment by DanielBeato** [comment]
Pues no sé a los demás, pero a mí esto me convence. Yo creo que vamos por el buen camino, vamos equipo!
