### ISSUE TITLE
Mudar algoritmo a Android

### ISSUE THREAD

**Issue by arc0067** [DanielBeato/GESPRO_PracticaGestionTareas_1718#50]
Mudar el algoritmo de visión artificial desarrollado en Java a Android.

**Comment by DanielBeato** [comment]
Muda muda múdalop, venga va, que te echo una mano

**Comment by arc0067** [comment]
Terminada la mudanza.

El algoritmo funciona correctamente.

Arroja tiempo de entre 50-80ms (x3 veces más lento que en el pc que eran de 10-30ms).
