### ISSUE TITLE
Icono home en colmenas no retrocede

### ISSUE THREAD

**Issue by jorgenavarroglez** [DanielBeato/GESPRO_PracticaGestionTareas_1718#57]
El icono home en `HivesActivity` no retrocede a `ApiariesActivity`.

**Comment by DanielBeato** [comment]
La solución podría estar en un caso similar que he encontrado por Internet: https://github.com/davidmigloz/go-bees/commit/7f665a1ff6a57f7e1fee59613bce2423da87e219

**Comment by jorgenavarroglez** [comment]
Voy a echarle un vistazo a ver si consigo solucionarlo, gracias

**Comment by jorgenavarroglez** [comment]
Gracias por la informacion Daniel, bug solucionado.
