### ISSUE TITLE
Detalle grabación

### ISSUE THREAD

**Issue by DanielBeato** [DanielBeato/GESPRO_PracticaGestionTareas_1718#68]

**Comment by mus0007** [comment]
Buenas compañero, en este issue  te voy a ayudar ya que veo que tu solo no vas a poder, cualquier duda que tengas avísame.

**Comment by DanielBeato** [comment]
Que buen compañero de trabajo eres @mus0007 por favor, si es que te pierde tu buena fe y tu don para ayudar a quienes te rodean.

**Comment by DanielBeato** [comment]
![image](https://user-images.githubusercontent.com/33248339/32970568-d766eb28-cbe9-11e7-868d-35135194aad2.png)
