### ISSUE TITLE
Prototipo inicial de la app

### ISSUE THREAD

**Issue by jng0020** [DanielBeato/GESPRO_PracticaGestionTareas_1718#7]
Realizar un prototipo de la interfaz gráfica de la app.

**Comment by DanielBeato** [comment]
Pues no sé a los demás, pero me parece mejor que te hayas puesto a dibujar el prototipo de la app porque te sentías  inspirado después de la siesta en lugar de buscar el coñazo de la bibliografía, que todo el mundo sabe que eso no se lo mira nadie. 
Ere un crack!

**Comment by jng0020** [comment]
![bee50606-779f-11e6-991d-3df83189f5ea](https://user-images.githubusercontent.com/33248327/32217381-10ff4e72-be28-11e7-8f6f-98c59f931cda.jpg)
![bed9edac-779f-11e6-9fbf-8cd4cfefff32](https://user-images.githubusercontent.com/33248327/32217382-111d2a82-be28-11e7-9272-695ed2238972.jpg)
![bedfebe4-779f-11e6-96d5-c804d38dc8b9](https://user-images.githubusercontent.com/33248327/32217383-113872d8-be28-11e7-95ee-e92754b1d4ac.jpg)
![bee395a0-779f-11e6-81ec-024b3c94d4cf](https://user-images.githubusercontent.com/33248327/32217385-11527e26-be28-11e7-9361-ae804496b898.jpg)
![bee81012-779f-11e6-9004-d17cd1a8a17d](https://user-images.githubusercontent.com/33248327/32217386-117ff8d8-be28-11e7-98b6-cae46db507f8.jpg)

**Comment by jng0020** [comment]
Gracias Dani!!! ya estamos Alisson y yo trabajando en ello.
